# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a5f5cc9985f027b0f35e160ab38dd51bd963745d9883883685b4e4beac615377d53c943dd08d9c2ffefe53f4aacd98324e3682ad70921eccec131ba1f45aaaa

test:
  secret_key_base: fc34f737c5472471a8cbe85d44f4d8ad99209966e32cfa5c0219a19849fc9a406e405643d147b39adbc11e038e0338e56375ba96cadc644c7da547d35f3287bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
